version: '3'
services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: "test"
      RABBITMQ_DEFAULT_PASS: "test"
    ports:
      - "5672:5672"
      - "15672:15672"

  go-api:
    build: .
    ports:
      - "8080:8000"
    env_file: .env