app:
  port: ':8000'

cryptoApi:
  url: 'https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest'
  headerName: 'X-CMC_PRO_API_KEY'

emailSending:
  senderAddress: 'krokkozerro@gmail.com'

database:
  filePath: './data/data.json'